---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-clamav
      # We do prepend the name of the role to the role variables, but
      # Molecule does its own role discovery with inconsistent naming.
      # This is the reason for the noqa below.
      ansible.builtin.include_role: # noqa var-naming[no-role-prefix]
        name: ansible-role-clamav
      vars:
        clamav_freshclam_configuration:
          DatabaseMirror: ['db.local.clamav.net', 'database.clamav.net', 'dummy.localhost']
          Bytecode:
        clamav_clamd_configuration:
          LogFile: /var/log/clamav/clamav.log
          StreamMaxLength: 22M
