---
- name: Backup {{ task_conf_file }} to {{ task_conf_file }}.{{ ansible_date_time.iso8601 }}
  ansible.builtin.copy:
    src: "{{ task_conf_file }}"
    dest: "{{ task_conf_file }}.{{ ansible_date_time.iso8601 }}"
    remote_src: true
  when: clamav_configuration_backup
  tags:
    - molecule-idempotence-notest

- name: Configure single-valued entries in {{ task_conf_file }}
  ansible.builtin.lineinfile:
    path: "{{ task_conf_file }}"
    line: "{{ item.key }} {{ item.value }}"
    search_string: "{{ item.key }} "
    state: present
  loop: "{{ task_conf_parameters | dict2items | selectattr('value','string') }}"

- name: Configure multi-valued entries in {{ task_conf_file }}
  ansible.builtin.lineinfile:
    path: "{{ task_conf_file }}"
    line: "{{ item.0.key }} {{ item.1 }}"
    state: present
  loop: "{{ task_conf_parameters | dict2items | rejectattr('value','string') | subelements( 'value' ) }}"

- name: Remove unwanted values from {{ task_conf_file }}
  ansible.builtin.lineinfile:
    path: "{{ task_conf_file }}"
    regexp: "^{{ item }} (?!{% for clamav_value in task_conf_parameters[item] %}{{ clamav_value | regex_escape() }}{{ '|' if not loop.last }}{% endfor %})"
    state: absent
  with_items: "{{ task_conf_parameters }}"

- name: Remove unwanted keys from {{ task_conf_file }}
  ansible.builtin.lineinfile:
    path: "{{ task_conf_file }}"
    regexp: "^{{ item }} .*$"
    state: absent
  loop: "{{ task_conf_parameters | dict2items | selectattr('value','none') }}"

- name: Set permissions on configuration file {{ task_conf_file }}
  ansible.builtin.file:
    path: "{{ task_conf_file }}"
    mode: 0700
