---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install ClamAV packages
  ansible.builtin.package:
    name: '{{ package_names }}'
    state: present

- name: Install virus_scan cron job
  ansible.builtin.copy:
    src: virus_scan.sh
    dest: /etc/cron.{{ clamav_cron_frequency }}/virus_scan
    mode: 0755

- name: Ensure that log folder exists
  ansible.builtin.file:
    path: /var/log/clamav
    state: directory
    mode: 0755

- name: Ensure log file will be world-readable
  ansible.builtin.file:
    access_time: preserve
    modification_time: preserve
    path: /var/log/clamav/lastscan.log
    state: touch
    mode: 0644

- name: Load tasks file with setup tasks based on the OS type
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - setup_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        # The ansible_distribution_release variable is always empty
        # for Fedora, so this is necessary since we want to do
        # something different for Fedora 34.
        - setup_{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml
        - setup_{{ ansible_distribution }}.yml
        - setup_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"

- name: Wait for new signatures to be downloaded and installed by freshclam
  ansible.builtin.wait_for:
    timeout: 600
    path: /var/lib/clamav/bytecode.cvd
    state: present
