---
# tasks file for clamav

- name: Install ClamAV package
  package: name=clamav-daemon state=present

- name: Modify ClamAV configuration
  blockinfile:
    path: /etc/clamav/clamd.conf
    state: present
    block: |
      ExcludePath ^/dev/
      ExcludePath ^/proc/
      ExcludePath ^/sys/

- name: Install virus_scan cron job
  copy: src="virus_scan.sh" dest="/etc/cron.weekly/virus_scan" mode=755

# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Set freshclam to start at boot
  service:
    name: clamav-freshclam
    enabled: yes
    state: started

- name: Wait for new signatures to be downloaded and installed by freshclam
  wait_for:
    timeout: 300
    path: /var/lib/clamav/bytecode.cvd
    state: present

- name: Set ClamAV to start at boot
  service:
    name: clamav-daemon
    enabled: yes
    state: started
