---
- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install ClamAV packages
  package:
    name: '{{ package_names }}'
    state: present

- name: Install virus_scan cron job
  copy:
    src: virus_scan.sh
    dest: /etc/cron.weekly/virus_scan
    mode: 0755

- name: Load tasks file with setup tasks based on the OS type
  include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - setup_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        - setup_{{ ansible_distribution }}.yml
        - setup_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"

- name: Wait for new signatures to be downloaded and installed by freshclam
  wait_for:
    timeout: 600
    path: /var/lib/clamav/bytecode.cvd
    state: present
