---
- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        # Add regex_replace() filters to remove spaces and
        # slashes. This allows the OS family/distribution for Kali,
        # "Kali GNU/Linux", to be easily mapped to a vars file.
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}.yml"
        - "{{ ansible_os_family | regex_replace('[ /]', '_') }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install ClamAV packages
  package:
    name: '{{ package_names }}'
    state: present

- name: Install virus_scan cron job
  copy:
    src: virus_scan.sh
    dest: /etc/cron.weekly/virus_scan
    mode: 0755

- name: Load tasks file with setup tasks based on the OS type
  include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        # Add regex_replace() filters to remove spaces and
        # slashes. This allows the OS family/distribution for Kali,
        # "Kali GNU/Linux", to be easily mapped to a vars file.
        - setup_{{ ansible_distribution | regex_replace('[ /]', '_') }}.yml
        - setup_{{ ansible_os_family | regex_replace('[ /]', '_') }}.yml
      paths:
        - "{{ role_path }}/tasks"

- name: Wait for new signatures to be downloaded and installed by freshclam
  wait_for:
    timeout: 600
    path: /var/lib/clamav/bytecode.cvd
    state: present
