---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install ClamAV packages
  ansible.builtin.package:
    name: '{{ package_names }}'
    state: present

- name: Install virus_scan cron job
  ansible.builtin.copy:
    dest: /etc/cron.{{ clamav_cron_frequency }}/virus_scan
    mode: 0755
    src: virus_scan.sh

- name: Ensure that log folder exists
  ansible.builtin.file:
    mode: 0755
    path: /var/log/clamav
    state: directory

- name: Ensure log file will be world-readable
  ansible.builtin.file:
    access_time: preserve
    mode: 0644
    modification_time: preserve
    path: /var/log/clamav/lastscan.log
    state: touch

- name: Load tasks file for systemd setup
  ansible.builtin.include_tasks: setup_systemd.yml
  when: ansible_service_mgr == 'systemd'

- name: Load tasks file for manual setup
  ansible.builtin.include_tasks: setup_manual.yml
  when: ansible_service_mgr != 'systemd'

- name: Wait for new signatures to be downloaded and installed by freshclam
  ansible.builtin.wait_for:
    path: /var/lib/clamav/bytecode.cvd
    state: present
    timeout: 600
