---
# Add kali-dev package repo
#
# TODO: These tasks should be removed once libtfm1>=0.13.1-1 is
# available in kali-rolling.  See #61 for more details.

- name: Add the kali-dev package repository
  ansible.builtin.apt_repository:
    repo: deb http://http.kali.org/kali kali-dev main contrib non-free

- name: Update the cache with the kali-dev goodness
  ansible.builtin.package:
    update_cache: yes
  # This cache update can cause idempotence to fail, so tell molecule
  # to ignore any changes this task produces when testing idempotence.
  tags:
    - molecule-idempotence-notest
