---
# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

# Debian seems to enable the clamav daemon by default
- name: Disable main clamav daemon
  ansible.builtin.service:
    name: "{{ clamav_service_name }}"
    enabled: no

# freshclam is run via a cron job on Fedora <34, so there is no
# service to start in that case
- name: Start and enable freshclam
  ansible.builtin.service:
    name: "{{ freshclam_service_name }}"
    enabled: yes
    state: started
