---
# This task runs freshclam and controls the virus database creation.
# It happens automatically with SystemD when registering freshclam service.

- name: Run freshclam
  ansible.builtin.command:
    cmd: /usr/bin/freshclam
    creates: /var/lib/clamav/bytecode.cvd
