---
- name: Restart freshclam service
  ansible.builtin.service:
    name: "{{ freshclam_service_name }}"
    state: restarted

- name: Restart clamd service
  ansible.builtin.service:
    name: "{{ clamd_service_name }}"
    state: restarted
