---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-clamav
      ansible.builtin.include_role:
        name: ansible-role-clamav
      vars:
        clamav_freshclam_conf:
          DatabaseMirror: ['db.local.clamav.net', 'database.clamav.net', 'dummy.localhost']
          Bytecode:
        clamav_clamd_conf:
          LogFile: /var/log/clamav/clamav.log
          StreamMaxLength: 22M
