---
- name: Import upgrade playbook
  import_playbook: upgrade.yml

- name: Import python playbook
  import_playbook: python.yml

# We want to copy a cron job to /etc/cron.daily, so that directory
# needs to exist.  In our Kali and Debian 11 images it does not, so we
# need to install a cron implementation.  On these platforms, the
# default cron package name is called cron.
- name: Group hosts by OS distribution
  hosts: all
  tasks:
    - name: Group hosts by OS distribution
      group_by:
        key: os_{{ ansible_distribution }}
- name: Install cron (Debian and Kali)
  hosts: os_Kali:os_Debian
  tasks:
    - name: Install cron
      package:
        name:
          - cron
